import type { Strategy } from "./types";

export const STRATEGIES: Strategy[] = [
  {
    slug: "vwap-bounce",
    name: "VWAP Bounce",
    tagline: "Mean-revert to the volume-weighted average price in a trending day.",
    horizon: "day",
    bias: "both",
    assetClasses: ["stock", "etf"],
    difficulty: "intermediate",
    tldr:
      "On a trending intraday session, buy pullbacks into VWAP (or short rallies into VWAP) when price rejects the level with a confirming candle. VWAP acts as the day's fair-value magnet — institutional algos defend it.",
    whenToLookFor: [
      "Clear intraday trend established (price held above/below VWAP for ≥ 30 min)",
      "Liquid name with > 1M average daily volume",
      "Mid-morning or post-lunch session (avoid the open/close noise)",
      "Pullback approaches VWAP without slicing through it on a single candle",
      "Day's range is at least 1× the 20-day ATR (you need movement to extract)",
    ],
    steps: [
      "Identify the trend direction: price closed multiple 5-min candles above VWAP = long bias.",
      "Wait for a pullback that touches or comes within 0.1× ATR of VWAP.",
      "Look for a rejection candle: hammer, bullish engulfing, or a strong close back above VWAP.",
      "Enter on the next candle's break above the rejection candle's high (long).",
      "Place the stop just below the rejection candle's low.",
      "Set the first target at 1× the risk distance; trail the rest with VWAP or a 9-EMA.",
      "Exit before the last 15 min of the session — VWAP setups don't survive into the close.",
    ],
    entry: "Break of the rejection candle's high (long) or low (short) on volume.",
    stop: "Just beyond the rejection candle's extreme — typically 0.1–0.3× ATR away.",
    target: "1× R for partials, trail rest with VWAP or 9-EMA.",
    rrTarget: "1:1 to 1:2",
    indicators: ["VWAP (session-anchored)", "9-EMA (trend filter)", "Volume profile", "ATR(14)"],
    pitfalls: [
      "Trading this on news/earnings days — VWAP gets sliced through and the level fails.",
      "Forcing it on a chop day (no trend) — every VWAP touch fails as both sides dominate.",
      "Sizing by share count instead of risk — a tight stop here means you can size up safely.",
    ],
    diagram: {
      points: [60, 64, 68, 72, 70, 65, 58, 54, 56, 62, 70, 76, 82, 80, 78, 84, 88],
      refLine: {
        points: [62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62],
        label: "VWAP",
      },
      highlights: [
        { x: 7, label: "VWAP touch" },
        { x: 9, label: "Rejection" },
        { x: 11, label: "Entry" },
      ],
      entryIdx: 11,
      stopY: 50,
      targetY: 86,
    },
  },

  {
    slug: "ema-pullback",
    name: "EMA Pullback",
    tagline: "Buy the dip to a fast EMA inside a strong trend.",
    horizon: "day",
    bias: "both",
    assetClasses: ["stock", "etf", "fx"],
    difficulty: "beginner",
    tldr:
      "When a clear short-term trend is in place, pullbacks to the 9- or 21-EMA frequently hold. Enter on the bounce, stop below the EMA, target a multiple of the recent leg.",
    whenToLookFor: [
      "Price has made at least 2 higher highs and higher lows on the timeframe (long bias)",
      "Both 9-EMA and 21-EMA are sloping in the trend direction",
      "Pullback retraces ≥ 38% of the prior leg (Fibonacci or eyeball)",
      "Volume drops on the pullback, confirming it's profit-taking — not distribution",
      "The 9-EMA hasn't been broken with strong volume in the past 10 candles",
    ],
    steps: [
      "Confirm the trend on a higher timeframe (e.g., 15-min trend for 5-min entries).",
      "Wait for price to retrace into the 9- or 21-EMA (whichever is being respected).",
      "Watch for a reversal candle at the EMA: pin bar, engulfing, or three-bar play.",
      "Enter on confirmation: a new high above the prior 1-2 candles for longs.",
      "Stop below the EMA AND below the recent swing low.",
      "First partial at 1R, trail the rest with the 9-EMA itself.",
      "Exit if price closes through both EMAs — the trend is breaking.",
    ],
    entry: "First candle that takes out the prior 1-2 candle highs after the EMA touch.",
    stop: "Below the 21-EMA OR the most recent swing low, whichever is wider.",
    target: "1.5–2R; trail with the 9-EMA after the first partial.",
    rrTarget: "1:1.5 to 1:3",
    indicators: ["9-EMA", "21-EMA", "Volume (declining on pullback)", "ATR for stop sizing"],
    pitfalls: [
      "Treating a sideways market as a trend — pullbacks never resolve, all stops out.",
      "Skipping the higher-timeframe check — entering against the bigger trend.",
      "Moving the stop too quickly to break-even before the trade can breathe.",
    ],
    diagram: {
      points: [40, 44, 48, 52, 56, 60, 58, 56, 54, 58, 64, 70, 68, 66, 70, 76, 82],
      refLine: {
        points: [40, 42, 44, 47, 50, 53, 54, 54, 54, 55, 58, 62, 64, 65, 67, 70, 74],
        label: "21-EMA",
      },
      highlights: [
        { x: 8, label: "EMA touch" },
        { x: 9, label: "Reversal" },
        { x: 11, label: "Entry" },
      ],
      entryIdx: 11,
      stopY: 50,
      targetY: 80,
    },
  },

  {
    slug: "bull-flag",
    name: "Bull Flag Breakout",
    tagline: "Strong rally, tight consolidation, breakout — the classic continuation pattern.",
    horizon: "swing",
    bias: "bull",
    assetClasses: ["stock", "etf"],
    difficulty: "beginner",
    tldr:
      "After a sharp upward move (the 'pole'), price consolidates sideways or in a slight downward channel (the 'flag'), then breaks out higher on volume. Measured-move target equals the pole's height added to the breakout point.",
    whenToLookFor: [
      "A strong move up of 15–40% over 5–20 sessions (the pole)",
      "Followed by a tight 5–15 day consolidation, ideally in a downward-sloping channel",
      "Volume contracts during the flag and expands on the breakout",
      "Above the rising 20-day SMA throughout the consolidation",
      "Sector or broad market is also constructive (don't fight the tape)",
    ],
    steps: [
      "Identify a clear pole: a sharp, near-vertical advance with above-average volume.",
      "Mark the flag boundaries with two trendlines connecting the consolidation highs and lows.",
      "Wait — many flags fail; the longer the tight range, the better.",
      "Enter on a daily close above the upper flag trendline AND above the prior swing high.",
      "Confirm volume on the breakout is at least 1.5× the 20-day average.",
      "Stop below the flag low (a close below invalidates the pattern).",
      "First target: pole height projected from the breakout point. Trail rest with 20-EMA.",
    ],
    entry: "Daily close above the upper flag trendline with confirming volume.",
    stop: "Below the lowest point of the flag consolidation.",
    target: "Pole height added to the breakout level (measured move); often 2–3R.",
    rrTarget: "1:2 to 1:4",
    indicators: ["20-day SMA (trend)", "Volume (contraction → expansion)", "Relative strength vs SPY"],
    pitfalls: [
      "Acting on intraday breakouts — wait for the daily close, false breaks are common.",
      "Trading flags in a weak sector — even good patterns fail without sector tailwinds.",
      "Missing the pivot when the pole was extended already — the move may be exhausting.",
    ],
    diagram: {
      points: [30, 32, 36, 44, 54, 64, 72, 78, 76, 74, 72, 70, 71, 73, 80, 88, 95],
      highlights: [
        { x: 0, label: "Base" },
        { x: 7, label: "Pole top" },
        { x: 11, label: "Flag low" },
        { x: 14, label: "Breakout" },
      ],
      entryIdx: 14,
      stopY: 68,
      targetY: 95,
    },
  },

  {
    slug: "ma-crossover",
    name: "20/50 MA Crossover",
    tagline: "When the 20-day SMA crosses the 50-day, ride the regime change.",
    horizon: "swing",
    bias: "both",
    assetClasses: ["stock", "etf"],
    difficulty: "beginner",
    tldr:
      "A bullish crossover (20-SMA above 50-SMA) signals a swing-trade-friendly uptrend; the bearish version signals a swing-short setup. Use as a filter — confirm with a pullback entry rather than chasing the cross itself.",
    whenToLookFor: [
      "20-day SMA crosses above (or below) the 50-day SMA on rising volume",
      "Both moving averages are sloping in the new direction",
      "Price closes above (below) both SMAs on the cross day",
      "The 200-day SMA agrees with the new trend — or at least doesn't fight it",
      "ADX is climbing, indicating a directional rather than chop regime",
    ],
    steps: [
      "Mark the crossover candle and verify both MAs are sloping in the trend direction.",
      "Don't enter at the cross — chase prevention. Wait for the first pullback.",
      "Pullback target: a touch of the 20-SMA from above (long) or below (short).",
      "Confirm a reversal candle at the SMA touch.",
      "Enter on the break of the reversal candle's high (long).",
      "Stop below the 50-SMA — if both averages are broken, the regime is failing.",
      "Target 2R minimum, then trail with the 20-SMA.",
    ],
    entry: "First pullback to the 20-SMA after the crossover, on a reversal candle.",
    stop: "Below the 50-SMA on a closing basis.",
    target: "2R first partial; trail with 20-SMA.",
    rrTarget: "1:2 to 1:5",
    indicators: ["20-day SMA", "50-day SMA", "200-day SMA (regime filter)", "ADX(14)"],
    pitfalls: [
      "Trading the cross itself — by the time it prints, the move is often extended.",
      "Ignoring the 200-SMA — long swings against the long-term trend have lower hit rates.",
      "Whipsaws in low-ADX environments — the cross prints, reverses, costs you twice.",
    ],
    diagram: {
      points: [50, 48, 46, 44, 42, 44, 48, 52, 56, 58, 56, 60, 66, 72, 70, 76, 82],
      refLine: {
        points: [55, 54, 53, 52, 51, 50, 50, 50, 51, 52, 53, 55, 57, 60, 62, 64, 66],
        label: "50-SMA",
      },
      highlights: [
        { x: 7, label: "Cross" },
        { x: 10, label: "Pullback" },
        { x: 12, label: "Entry" },
      ],
      entryIdx: 12,
      stopY: 50,
      targetY: 82,
    },
  },

  {
    slug: "oversold-reversal",
    name: "Oversold Reversal",
    tagline: "Buy capitulation in a quality name, with confirmation — not on hope.",
    horizon: "swing",
    bias: "bull",
    assetClasses: ["stock", "etf"],
    difficulty: "advanced",
    tldr:
      "When a fundamentally healthy stock pulls back hard into oversold territory (RSI < 30) and prints a reversal candle on rising volume, mean-reversion gives a high-probability swing entry. This is NOT a strategy for falling-knife garbage — quality matters.",
    whenToLookFor: [
      "Daily RSI(14) below 30 for at least 2 consecutive sessions",
      "Stock is in a long-term uptrend (above 200-day SMA, ideally) — this is a pullback, not a downtrend",
      "Volume spikes on the down move (capitulation — sellers exhausting)",
      "A clear reversal candle: hammer, bullish engulfing, or morning star at the lows",
      "No upcoming earnings or major news in the next 5 sessions",
    ],
    steps: [
      "Filter for quality first: 200-day SMA up, healthy fundamentals, sector not collapsing.",
      "Wait for RSI(14) to drop below 30 — don't anticipate.",
      "Watch for capitulation volume on the down candle (1.5× average or more).",
      "Look for the reversal candle with a clear bullish pattern at the daily low.",
      "Enter on the break of the reversal candle's high.",
      "Stop just below the reversal candle's low — usually a tight stop given the spike.",
      "First target: prior swing high or 50-SMA, whichever is closer. Trail rest.",
    ],
    entry: "Break of reversal-candle high on volume, with RSI turning up from < 30.",
    stop: "Below the reversal candle's low — break = invalid.",
    target: "Prior swing high or 50-SMA. Often 2-3R.",
    rrTarget: "1:2 to 1:3",
    indicators: ["RSI(14)", "200-day SMA (regime filter)", "Volume", "Bollinger Bands (oversold confirmation)"],
    pitfalls: [
      "Catching falling knives in genuine downtrends — the 200-SMA filter exists for this reason.",
      "Buying RSI < 30 without a reversal candle — RSI can stay oversold for weeks.",
      "Trading this through earnings — gap risk demolishes the tight-stop math.",
    ],
    diagram: {
      points: [80, 76, 70, 64, 56, 48, 40, 32, 26, 30, 38, 46, 54, 60, 64, 70, 75],
      highlights: [
        { x: 7, label: "RSI < 30" },
        { x: 8, label: "Capitulation low" },
        { x: 9, label: "Reversal" },
        { x: 10, label: "Entry" },
      ],
      entryIdx: 10,
      stopY: 22,
      targetY: 75,
    },
  },

  {
    slug: "golden-cross-dca",
    name: "Golden Cross DCA",
    tagline: "When the 50-SMA crosses above the 200-SMA, scale into the trend over weeks.",
    horizon: "long",
    bias: "bull",
    assetClasses: ["stock", "etf"],
    difficulty: "beginner",
    tldr:
      "The Golden Cross (50-day SMA crossing above the 200-day SMA) is one of the most-watched long-term regime signals. Rather than buying a lump sum at the cross, dollar-cost-average into the position over the following 2–6 weeks while the trend confirms.",
    whenToLookFor: [
      "50-day SMA crosses above the 200-day SMA",
      "Both SMAs are sloping upward — flat or downward 200-SMA is a weaker signal",
      "Broad market (SPY) is also above its 200-SMA",
      "ETF or established large-cap (don't apply this to penny stocks)",
      "Macro conditions reasonable — Fed not actively tightening into a recession",
    ],
    steps: [
      "Confirm the cross on a daily close basis — intraday crosses can reverse.",
      "Decide your full position size based on portfolio risk (typically 5–10% per long-term hold).",
      "Split the position into 4–6 tranches across the next 2–6 weeks.",
      "Buy the first tranche on the cross confirmation.",
      "Subsequent tranches on weekly closes that hold above the 50-SMA.",
      "If price closes below the 200-SMA at any point, stop adding — possibly exit.",
      "No fixed target — hold while the regime is intact (50 > 200, both sloping up).",
    ],
    entry: "First daily close after the 50-SMA crosses the 200-SMA. Add weekly thereafter.",
    stop: "Daily close below the 200-SMA invalidates the regime — exit or pause adds.",
    target: "Open-ended — exit on death cross (50 below 200) or fundamental thesis change.",
    rrTarget: "Open (regime-based)",
    indicators: ["50-day SMA", "200-day SMA", "Weekly trend", "Sector relative strength"],
    pitfalls: [
      "Buying the cross late after a huge run — wait for a pullback if extended.",
      "Stacking the full position on day one — DCA is the whole point.",
      "Ignoring macro deterioration — the cross can fail in tightening cycles.",
    ],
    diagram: {
      points: [40, 38, 36, 38, 42, 44, 48, 50, 54, 60, 64, 68, 72, 75, 78, 82, 86],
      refLine: {
        points: [50, 49, 48, 46, 45, 44, 43, 43, 44, 45, 47, 50, 53, 57, 61, 65, 69],
        label: "200-SMA",
      },
      highlights: [
        { x: 7, label: "Cross" },
        { x: 8, label: "Tranche 1" },
        { x: 11, label: "Tranche 2" },
        { x: 14, label: "Tranche 3" },
      ],
      entryIdx: 8,
      targetY: 90,
    },
  },
];

export function findStrategy(slug: string): Strategy | undefined {
  return STRATEGIES.find((s) => s.slug === slug);
}
